# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8373f29f5a5a9e8ee16e28761f429706eef1a0aa98a358c5d2242924553baf79ec421175e3e13e5d0ace50ce55d864edeff1e20a6f5a9bd31bb1cc334849d51

test:
  secret_key_base: 447cb3f923e1c23ed88134ba643b59068d17ecbbed4b9bebe75d6ed753014e65f6426cb0affe704d9229db03173be112216bccad758bb8ce9dbd8493d93515da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
